create table user (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  nomdecompte varchar(255) NOT NULL UNIQUE,
  hashed_password VARCHAR(255) NOT NULL
);

create table Exercices (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  video_path VARCHAR(255),
  muscle_group VARCHAR(255),
  instruction TEXT,
  equipment TEXT,
)

create table user_exos (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  exercice_id INT NOT NULL,
  FOREIGN KEY (user.id) REFERENCES user(id) ON DELETE CASCADE,
  UNIQUE (user_id, exercice_id)
)

INSERT INTO user (nomdecompte, hashed_password) VALUES ('AdminTest', 'AdminTest')

INSERT INTO Exercices (name, video_path, muscle_group, instruction, equipment) VALUES 
("Abs Wheel", "/videos/Abdos/AbsWheelBarre.mp4", "Abdominaux", "1- Placez vos genoux au bord du tapis de yoga. </br> 2- Placez vos mains de chaque côté de la roulette et placez la roulette au niveau de vos genoux. </br> 3- Faites rouler cette dernière vers l'avant tout en maintenant vos genoux sur le sol, vos bras tendus et vos abdominaux contractés. </br> 4- Une fois la roulette avancée au maximum de vos capacités revenez en position de départ. </br> 5- Attention à ne pas creuser le dos, c'est vos épaules et vos hanches qui doivent excécuter le mouvement de l'Ab Wheel (si vous avez des problèmes de dos comme lombalgie, hernie discale, sciatique, scoliose, etc, il est fortement déconseillé de pratiquer cet exercice.", "- Ab roller wheel. </br> - Tapis de yoga."),
("Crunch sur banc décliné avec haltère", "/videos/Abdos/CrunchAvecHaltere.mp4", "Abdominaux", "1- Réglez la déclinaison du banc aux alentoirs de 35 degrés (plus le banc est décliné plus la difficulté sera grande), bloquez vos jambes au sommet du banc (les genoux devraient former un amgle à 90°), allongez-vous en veillant à plaquer le dos bien à plat contre le dossier, saisissez l'haltère et posez le contre votre poitrine </br> 2- Contractez le bas des abdominaux de manière à décoller les épaules du banc, pour cela, enrouler le buste et arrondissez le dos. </br> 3- Poussez aussi fort que possible jusqu'à lever le haut du corps afin qu'il fasse un angle droit avec vos jambes, tout en gardant le bas du dos en contact avec le banc. </br> 4- Au sommet du mouvement, contractez les abdominaux pendant une seconde, redescendez ensuite le buste en contrôlant la descente jusque dans la position de départ. </br> 5- Expirez durant la phase de montée et inspirez durant la phase de descente.", "- Banc décliné. </br> - Haltère."),
("Crunch allongé avec haltères", "/videos/Abdos/CrunchLestee.mp4", "Abdominaux", "1- Allongez vous sur un tapis de yoga, les jambes pliées et les piedsbloqués par un obstacle. </br> 2-Prenez un haltère dans chaque main et tendez les bras. </br> 3- Tout en contractant les abdominaux relevez le buste, tout en laissant vos bras perpendiculaire au sol passez votre tête entre vos bras. </br> 4- Tenez la position en contractant les abdominaux pendant une seconde puis descendez en contrôlant le mouvement afin de revenir à la position de départ. </br> 5- Expirez durant la montée et inspirez durant la descente.", "- Haltères. </br> - Tapis de yoga."),
("Crunch à la machine", "/videos/Abdos/CrunchMachine.mp4", "Abdominaux", "1- Sélectionnez le poids que vous souhaitez utiliser pour effectuer l'exercice (ne mettez pas trop de poids afin de ne pas solliciter les muscles flechisseurs des hanches). </br> 2- Asseyez vous en plaçant vos pieds soit sur la plaque soit derrière les boudins puis attrapez les poignées. </br> 3- Enroulez le buste en contractant les abdominaux fortement en rapprochant la poitrine de vos jambes. </br> 4- Maintenez la contraction pendant une seconde puis revenez lentement dans la position initiale de façon contrôlée. </br> 5- Ne bloquez pas votre respiration pendant l'excercice, soufflez en enroulant le buste et inspirez en relachant la contraction.", "- Machine à crunchs"),
("Crunch à la poulie", "/videos/Abdos/CrunchPoulieHaute.mp4", "Abdominaux", "1- Placez vous à genoux suffisamment éloigné de la poulie afin de pouvoir baisser votre buste sans soucis. </br> 2- Choisissez un poids suffisant pour effectuer le mouvement (ne prenez pas trop lourd pour ne pas un mauvais mouvement). </br> 3- Saisissez la barre les paumes de main vers le ciel et gardez vos coudes à côté de vos oreilles. </br> 4- Expirez tout en contractant vos abdominaux afin d'enrouler le buste vers vos jambes. </br> 5- Maintenez la contraction pendant une seconde et expirez en contrôlant lentement le mouvement afin de revenir en position initiale", "- Poulie"),
("Crunch haltère avec jambes levées", "/videos/Abdos/JambesLeveeCrunchHaltere.mp4", "Abdominaux", "1- Allongez vous sur le dos et tendez vos jambes à 90° par rapport au sol. </br> 2- Prenez un poids entre vos mains et tendez les mains devant vous à 90° par rapport au sol. </br> 3- Contractez les abdominaux et levez le buste afin d'amener le poids vers les pieds sans bouger les jambes. </br> 4- Gardez la contraction pendant une seconde puis reprenez lentement la position de départ. </br> 5- Expirez bien lors de la contraction et inspirez lors du relâchement.", "- Haltère. </br> - Tapis de yoga."),
("Levé de bassin sur banc", "/videos/Abdos/LeveDeBassinSurBanc.mp4", "Abdominaux", "1- Allongez vous sur un banc, maintenez le banc avec vos main placées au niveau de la tête. </br> 2- Mettez vos jambes en angle droit avec le banc et vos tibias en angle droit par rapport à vos jambes. </br> 3- Tout en expirant amenez vos genoux vers votre poitrine. </br> 4- Relachez lentement tout en inspirant afin de revenir à la position initiale. </br> 5- Attention ! Veillez bien à ne pas creuser le bas du dos.", "- Banc"),
("Levée de jambes", "/videos/Abdos/LeveDeJambes.mp4", "Abdominaux", "1- Allongez vous sur la tapis de yoga, bras le long du corps. </br> 2- Expirez votre air tout en montant vos jambes jusqu'à former un angle de 45°. </br> 3- Inspirez et baissez vos jambes afin de les reposer au sol. </br> 4- Veillez bien à ne pas creuser le bas du dos.", "- Tapis de yoga"),
("Levée de jambes (Chaise Romaine)", "/videos/Abdos/LeveDeJambesPupitre.mp4", "Abdominaux", "1- Placez vous sur la chaise romaine, le dos contre le dossier, la tête bien droite, regardez droit devant. </br> 2- Au moment de l'expiration levez vos jambes, tout en les gardant tendues, jusqu'à ce qu'elles forment un angle droit avec votre corps. </br> 3- Inspirez tout en faisant redescendre vos jambes afin d'être droit. </br> 4- Veillez à ne pas faire de mouvement de balancier.", "- Chaise Romaine"),
("Flexions latérales à la poulie basse", "/videos/Abdos/TiragePoulieBasse.mp4", "Abdominaux", "1- Placez la poulie en position basse, choisissez un poid afin que vous ne soyez pas en difficulté. </br> 2- Placez vous de façon à ce que la poulie soit sur le côté de votre corps. </br> 3- Écartez vos pieds largeur d'épaules, fléchissez légèrement les jambes. </br> 4- Au début du mouvement votre corps est penché sur le côté, vous allez expirer tout en redressant votre corps. </br> 5- Vous allez accompagner les poids en penchant lentement votre buste tout en inspirant afin de revenir à la position initiale.", "- Poulie"),
("Flexion des poignets sur banc", "/videos/Avant-Bras/AvantBrasCurlSurBanc.mp4", "Avant-bras", "1- Asseyez-vous sur une chaise avec l’avant-bras posé sur une surface stable, comme le dessus d’une table ou le genou, la paume tournée vers le haut. </br> 2- Vous pouvez utiliser un haltère léger ou un autre petit poids pour cet exercice. </br> 3- Sans bouger l’avant-bras, pliez lentement le poignet vers le haut, rapprochant le plus possible le poids de l’avant-bras. </br> 4- Assurez-vous que le mouvement est contrôlé et centré sur le poignet. </br> 5- Abaissez lentement le poids en étendant le poignet, revenant à la position de départ. </br> 6- Répétez l’exercice plusieurs fois selon votre niveau de confort et de capacité.", "- Banc. </br> - Haltères."),
("Flexion des poignets avec une barre", "/videos/Avant-Bras/AvantBrasCurl.mp4", "Avant-bras", "1- Debout, jambes écartés largeur du bassin. </br> 2- Prenez la barre dans votre dos. </br> 3- Vous allez laisser glisser la barre de long de vos doigts (sans la faire tomber), puis serrez vos mains afin de resserer votre poigne sur la barre.", "- Barre avec des poids"),
("Flexion des poignets à la poulie", "/videos/Avant-Bras/ForArmPoulie.mp4", "Avant-bras", "1- Placez la poulie en position basse équipée de la barre droite. </br> 2- Placez vous dos à la poulie afin d'avoir la barre droite au niveau de vos fesses. </br> 3- Laissez la barre vous glisser délicatement des doigts sans la lâcher. </br> 4- Resserez vos mains afin de renforcer la prise sur la barre.", "- Poulie"),
("Extension des poignets sur banc", "/videos/Avant-Bras/AvantBrasCurlSurBanc.mp4", "Avant-bras", "1- Asseyez-vous avec l’avant-bras appuyé sur une table ou sur votre genou, paume tournée vers le bas. </br> 2- Utilisez un haltère léger pour ajouter une résistance adaptée à votre force. </br> 3- Soulevez lentement votre poignet vers le haut, en étendant aussi loin que possible sans bouger l’avant-bras. </br> 4- Le mouvement doit être fluide et contrôlé, mettant l’accent sur l’extension complète du poignet. </br> 5- Ramenez doucement le poids en position de départ, en permettant à votre poignet de revenir en flexion neutre. </br> 6- Répétez pour le nombre de répétitions souhaité, en veillant à ne pas surcharger les muscles.", "- Banc. </br> - Haltères."),
("Curl inversé avec barre EZ", "/videos/Avant-Bras/CurlPronation.mp4", "Avant-bras, biceps", "1- Debout, le dos bien droit, les omoplates sérrées, les jambes largeur de bassin et légèrement fléchies, prenez la barre avec une prise pronation (paumes vers le bas). </br> 2- Avec les coudes posés, soulevez la barre vers vos épaules en gardant les poignets droits et stables. </br> 3- Concentrez-vous sur l’engagement des muscles des avant-bras et des biceps tout au long du mouvement. </br> 4- Abaissez lentement la barre en position de départ de manière contrôlée, en veillant à maintenir la tension dans les muscles des avant-bras.", "- Barre EZ avec des poids"),
("Curl debout alterné avec hatlères", "/videos/Biceps/CurlAlterneHaltere.mp4", "Biceps", "1- Saisissez une paire d’haltères et mettez-vous debout en tenant les haltères le long de votre corps. </br> 2- Écartez vos jambes largeur de bassin et fléchissez les légèrement. </br> 3- Vos bras doivent être légèrement fléchis et vos paumes tournées vers l’intérieur de votre corps (pouces vers l’avant). </br> 4- En commençant par votre bras le plus faible (généralement le gauche), contractez votre biceps pour monter l’haltère vers le haut. </br> 5- Pendant la flexion, faites pivoter l’haltère pour passer d’une position neutre (paumes vers l’intérieur) à une position en supination (paumes vers le haut). </br> 6- Contractez votre biceps en haut du mouvement, puis redescendez lentement l’haltère sans le laisser toucher votre corps. </br> 7- Veillez à garder le coude fixe, c'est l'avant-bras qui doit faire le mouvement.", "- Haltères"),
("Curl debout à la barre", "/videos/Biceps/CurlBarre.mp4", "Biceps", "1- Prenez la barre en prise supination (paume de main vers le ciel). </br> 2- Gardez le dos droit et un minimum de flexion sur les genoux. Vos jambes doivent être espacés à la largeur des hanches. </br> 3- Positionnez vos mains aussi large que vos épaules. Puis montez la charge en gardant les coudes collés au corps. </br> 4- Revenez en position de départ en redescendant la barre. Le tempo doit être lent et controlé. </br> 5- Il faut que les charges soit adaptés de façon à ce que vous n’ayez pas besoin de faire un élan, car ce mouvement n’est pas idéal pour votre dos.", "- Barre avec des poids"),
("Curl debout à la poulie basse", "/videos/Biceps/CurlBarrePoulieBasse.mp4", "Biceps", "1- Placez la poulie en position basse avec la barre droite. </br> 2- Prenez la barre en prise supination (paume de main vers le ciel). </br> 3- Gardez le dos droit et un minimum de flexion sur les genoux. Vos jambes doivent être espacés à la largeur des hanches. </br> 4- Montez la charge en gardant les coudes collés au corps. </br> 5- Revenez en position de départ en redescendant la barre. Le tempo doit être lent et controlé.", "- Poulie"),
("Curl alterné sur banc incliné avec haltères", "/videos/Biceps/CurlHaltereSurBancIncline.mp4", "Biceps", "1- Assayez-vous sur le banc en position incliné et saisissez les haltères dans chaque mains. </br> 2- Tout en gardant les coudes fixe contractez le biceps en ramenant l'haltère vers votre épaule. </br> 3- Gardez la contraction pendant une seconde, puis relachez lentement afin de revenir en position initiale. </br> 4- Veillez bien à garder le coude fixe, sans faire un mouvement de balancier.", "- Banc. </br> - Haltères."),
("Curl debout prise marteau avec haltères", "/videos/Biceps/CurlMarteauHaltere.mp4", "Biceps, avant-bras", "1- Placez vous debut, pieds largeur de bassin, genoux légèrement fléchis. </br> 2- Saisissez les haltères et placez les bras le long du corps (paumes de mains vers votre corps). </br> 3- Amenez l'haltère vers l'épaule tout en gardant le coude bien fixe. </br> 4- Maintenez la contraction pendant une seconde, puis relachez pour revenir en position initiale. </br> 5- Veillez à bien garder les coudes fixes", "- Haltères"),
("Curl alterné sur banc incliné prise marteau avec haltères", "/videos/Biceps/CurlMarteauSurBancIncline.mp4", "Biceps, avant-bras", "1- Placez vous debut, pieds largeur de bassin, genoux légèrement fléchis. </br> 2- Saisissez les haltères et placez les bras le long du corps (paumes de mains vers votre corps). </br> 3- Amenez l'haltère vers l'épaule tout en gardant le coude bien fixe. </br> 4- Maintenez la contraction pendant une seconde, puis relachez pour revenir en position initiale. </br> 5- Veillez à bien garder les coudes fixes", "- Haltères"),
("Curl unilatéral à la poulie basse", "/videos/Biceps/CurlPoulie.mp4", "Biceps", "1- Placez la poulie en position basse et mettez vous dos a celle-ci. </br> 2- Prenez la poignée dans une main, il faut que le bras soit légèrement tendue vers l'arrière pour garder une tension sur le biceps. Écartez vos jambes largeur de bassin et gardez une flexion légère des genoux. </br> 3- Contractez le biceps en amenant la poignée vers l'épaule, gardez la contraction pendant une seconde avant de relacher. </br> 4- Contrôlez le mouvement afin de revenir à la position initiale. </br> 5- Veillez a bouger le coude le moins possible.", "- Poulie"),
("Curl pupitre avec haltères", "/videos/Biceps/CurlPupitreHaltere.mp4", "Biceps", "1- Chargez la barre présente sur le pupitre à votre convenance. </br> 2- Placez vous derrière le pupitre, saisissez la barre mains en prise supination (paume de mains vers le ciel) de largeur d'épaules, décollez la barre et assayez-vous. </br> 3- Contractez le biceps en rapprochant la barre de votre menton tout en expirant votre air. </br> 4- Inspirez en relachant le mouvement lentement afin de revenir à la position initiale. </br> 5- Veillez à ne pas tendre complètement les bras afin de vous éviter une blessure.", "- Pupitre. </br> - Haltères."),
("Curl pupitre à la machine", "/videos/Biceps/CurlPupitreMachine.mp4", "Biceps", "1- Choisissez le poids avec lequel vous allez faire l'exercice et placez vous derrière le pupitre. </br> 2- Saisissez les poignées de la machine et décollez les poids puis assayez-vous. </br> 3- Contractez les biceps en ramenant les poignées vers le menton, effectuez le mouvement tout en expirant votre air. </br> 4- Inspirez en relachant le mouvement tout en le contrôlant afin de revenir à la position initiale. </br> 5- Veillez à ne pas tendre complètement les bras pour vous éviter toutes blessures.", "- Curl machine"),
("Curl barre sur banc à la poulie", "/videos/Biceps/CurlSurBancPoulie.mp4", "Biceps", "1- Placez le banc incliné face à la poulie qui aura été placée au préalable en position basse. </br> 2- Prenez en main la barre de la poulie en prise supination (paumes de mains vers le ciel) puis assayez-vous sur le banc afin d'avoir les bras tendus. </br> 3- Contractez les biceps en amenant la barre vers motre menton tout en expirant votre air. </br> 4- Relâchez ensuite lentement afin de revenir à la position initiale tout en inspirant. </br> 5- Veillez à garder les coudes fixes et omoplates serrées.", "- Poulie"),
("Curl unilatéral à la poulie vis-à-vis", "/videos/Biceps/CurlUnilateralpoulieHaute.mp4", "Biceps", "1- Placez la poulie en position haute puis mettez vous de côté par rapport à la poulie. </br> 2- Prenez la poignée et tendez votre bras sur le coté afin que votre bras soit aligné avec votre corps et la poulie. </br> 3- Maintenez fixes votre épaule et votre coude, c'est votre avant-bras qui fera le mouvement. </br> 4- Contractez votre biceps en amenant la poignée vers votre oreille. </br> 5- Relâchez tout en contrôlant le mouvement afin de revenir à la position initiale. </br> 6- Veillez à bien expirer lors de la contraction et inspirer lors du relâchement.", "- Poulie"),
("Curl à la poulie vis-à-vis", "/videos/Biceps/DoubleTiragePoulieHaute.mp4", "Biceps", "1- Placez les deux poulies en position haute et mettez vous au centre. </br> 2- Prenez les poignets et tendez vos bras sur les côtés afin que vos bras soient alignés avec votre corps et les poulies. </br> 3- Maintenez fixes vos épaules et vos coudes, c'est vos avants-bras qui feront le mouvement. </br> 4- Contractez vos biceps en amenant les poignées vers vos oreilles. </br> 5- Relâchez tout en contrôlant le mouvement afin de revenir en position initiale. </br> 6- Veillez à bien expirer lors de la contraction et inspirer lors du relâchement.", "- Poulie"),
("Crul avec corde à la poulie", "/videos/Biceps/PriseMarteauPoulie.mp4", "Biceps, avant-bras", "1- Placez la poulie en position basse et accrochez y une corde. </br> 2- Placez vous face à la poulie et saisissez la corde en main en prise marteau (paumes de main vers votre corps). </br> 3- Gardez le dos droit, les jambes écartées largeur de bassin, genoux fléchis. </br> 4- Lors de la contraction amenez la corde vers le menton tout en gardant les coudes fixes. </br> 5- Vers la fin du mouvement faites une rotation du poignet afin que vos paumes de main soient tournées vers le ciel. </br> 6- soufflez en relâchant le mouvement et revenez à la position initiale. </br> 7- Veillez bien à expirer lors de la contraction et inspirer lors du relâchement, gardez les coudes fixes et faire une rotation des poignets à la fin du mouvement de contraction.", "- Poulie"),
("Spider Curl avec haltères en prise marteau", "/videos/Biceps/SpiderCulrMarteauHaltere.mp4", "Biceps, avant-bras", "1- Prenez un haltère dans chaque mains et installez votre poitrine sur le haut du banc incliné. </br> 2- Paumes de mains vers votre corps, jambes de chaque côtés du banc et les omoplates serrées. </br> 3- Montez les haltères vers les épaules tout en expirant votre air et en gardant les coudes fixes. </br> 4- Inspirez en relâchant lentement et en reprenant la position initiale. </br> 5- Veillez bien à garder les coudes fixes et les omoplates serrées.", "- Banc. </br> - Haltères."),
("Spider Curl à la barre", "/videos/Biceps/SpiderCurlBarre.mp4", "Biceps", "1- Placez un second banc devant le premier(le premier qui aura préalablement été incliné), afin d'y poser la barre chargée de poids à votre convenance. </br> 2- Placez votre buste sur le haut du dossier du banc incliné et placez vos jambes pour avoir une bonne stabilité. </br> 3- Saisissez vous de la barre en prise supination (paume de mains vers le ciel), décollez la barre du banc et serrez les omoplates. </br> 4- Expirez tout en contractant vos biceps afin d'amener la barre vers votre menton. </br> 5- Inspirez et relâcher lentement afin de revenir à la position initiale. </br> 6- Veillez a bien garder les omoplates serrées et les coudes fixes.", "- Banc. </br> - Barre avec des poids."),
("Spider Curl avec haltères", "/videos/Biceps/SpiderCurlHaltere.mp4", "Biceps", "1- Prenez un haltère dans chaque mains et installez votre poitrine sur le haut du banc incliné. </br> 2- Placez vos jambes de chaque côtés du banc afin d'avoir une bonne stabilité, laissez pendre vos bras et gardez les omoplates serrées. </br> 3- Paumes de mains vers le ciel montez les haltères vers les épaules tout en expirant et en gardant les coudes fixes. </br> 4- Inspirez en relâchant lentement et en reprenant la position initiale. </br> 5- Veillez bien à garder les coudes fixes et les omoplates serrées.", "- Banc. </br> - Haltères."),
("Spider Curl à la poulie basse", "/videos/Biceps/SpiderCurlPoulieBasse.mp4", "Biceps", "1- Positionnez le banc face à la poulie qui aura été mise en position basse et accrochez y la barre droite. </br> 2- Saisissez la barre et placez vous sur le banc incliné, le torse sur le haut du banc </br> 3- Les mains en prise supination (paumes de mains vers le ciel) contractez le biceps tout en expirant afin d'amener la barre vers le menton. </br> 4- Gardez la contraction durant une seconde puis relâchez lentement tout en inspirant. </br> 5- Veillez à garder les coudes fixes, ce sont les avants-bras qui font tout le mouvement, veillez également à garder les omoplates serrées.", "- Banc. </br> - Poulie."),
("Course à pied", "/videos/Cardio/CourseSurTapis.mp4", "Cardio", "1- Commencez par mettre une vitesse lente afin de marcher pour faire augmenter votre rythme cardiaque. </br> 2- Après avoir marché entre cinq et dix minutes vous pouvez augmenter la vitesse afin de courir. </br> 3- Une fois votre temps de course à pieds terminée ne stoppez pas immédiatement le tapis, revenez à une vitesse lente afin de marcher et faire redescendre votre rythme cardiaque. </br> 4- Veillez à bien vous échauffer avant et faire redescendre votre rythme cardiaque en fin de course.", "- Tapis de course"),
("Marche rapide sur tapis incliné", "/videos/Cardio/MarcheSurTapis.mp4", "Cardio", "1- Placez vous sur le tapis et mettez le en marche à une vitesse raisonnable. </br> 2- Après cinq à dix minutes de marche, afin de faire monter votre ryhtme cardiaque, augmentez l'inclinaison du tapis (ne pas dépasser 5% d'inclinaison). </br> 3- Une fois votre temps de marche terminée, continuer de marcher cinq minutes en ayant de nouveau le tapis a 0% d'inclinaison afin de faire redescendre votre ryhtme cardiaque. </br> 4- Veillez à bien vous échauffer avant et faire redescendre votre rythme cardiaque en fin de marche.", "- Tapis de course"),
("Stepper", "/videos/Cardio/Stepper.mp4", "Cardio", "1- Placez un pied à plat et en toute sécurité sur chaque marche. </br> 2- Appuyez un pied sur le stepper pendant que l’autre remonte. Répétez cette action avec le pied opposé. La sensation doit être similaire à celle de la montée des escaliers. </br> 3- Commencez lentement et augmentez la vitesse au fur et à mesure que vous vous habituez à la machine. Commencez votre séance d’entraînement entre cinq et dix minutes. Avec le temps, vous pouvez vous entraîner sur la machine pendant plus de 30 minutes.", "- Stepper"),
("Vélo", "/videos/Cardio/Velo.mp4", "Cardio", "1- Placez vous sur le vélo après avoir rélgé la selle de manière à ce que vos jambes soient tendues quand vous avez vos pieds de placés sur les pédales. </br> 2- Commencez à pédaler sans mettre trop de force afin de monter votre ryhtme cardiaque. </br> 3- Une fois bien échauffé vous pouvez augmenter la vitesse de pédalage ou la force. </br> 4- Après votre effort n'arrêtez pas de suite, baissez l'intensité afin de faire redescendre votre rythme cardiaque.", "- Vélo"),
("Vélo éllyptique", "/videos/Cardio/VeloEllyptique.mp4", "Cardio", "1- Placez vous sur le vélo éllyptique, mettez vos mains sur les poignées et commencez à pédaler. </br> 2- Après vous être échauffé cinq à dix minutes, afin d'augmenter votre ryhtme cardiaque, vous pouvez augmenter la résistance. </br> 3- Une fois votre entraînement terminé n'arrêtez pas de suite, baisser la résistance afin de faire redescendre votre rythme cardiaque.", "- Vélo ellyptique"),
("Chaise à Lombaires", "/videos/Dos/LombairesPupitre.mp4", "Dos", "1- Placez-vous sur la chaise à lombaires et placez le boudin sur l'arrière des jambes au niveau des mollets. </br> 2- Penchez votre corps vers le sol, contractez les abdos afin de ne pas creuser le bas du dos. </br> 3- Montez votre haut du corps afin d'aligner vos jambes avec le haut du corps. </br> 4- Gardez la contraction durant une seconde puis relâchez lentement afin de revenir proche du sol à la position initiale. </br> 5- Veillez à bien contractez pour ne pas cambrer le bas du dos.", "- Chaise à lombaires"),
("PullOver sur banc avec haltère", "/videos/Dos/PullOverHaltere.mp4", "Dos, pecs", "1- Prenez un haltère et allongez vous sur le banc. Prenez l'haltère avec les deux mains et tendez les bras au dessus de la poitrine. </br> 2- Gardez les bras tendus et faites basculer l'haltère vers le sol en passant les bras de chaque côtés de la tête afin d'aligner les bras avec le corps. </br> 3- Tout en gardant les bras tendus remonter les bras en arc de cercle afin de revenir en position bras tendus au dessus de la poitrine. </br> 4- Veillez à garder les fesses en contact avec le banc, inspirez au moment de la descente des bras et expirer au moment de remonter.", "- Banc. </br> - Haltère."),
("PullOver à la poulie haute", "/videos/Dos/PullOverPoulieHaute.mp4", "Dos", "1- Placer la poulie en position haute et accrochez-y la barre droite. </br> 2- Placez les pieds largeur de bassin, flechissez les genoux et penchez votre buste afin que les bras soient tendus quand vous saisissez la barre. </br> 3- contractez les abdominaux au moment du mouvement pour éviter de creuser le dos. </br> 4- Faites un arc de cercle avec les bras tendus afin d'amener la barre au niveau de vos cuisses tout en expirant. </br> 5- Faites le mouvement inverse lentement en inspirant afin de revenir à la position initiale. </br> 6- Veillez à bien gainer, expirer à la contraction et inspirer lors du relâchement", "- Poulie"),
("PullOver sur banc à la poulie haute", "/videos/Dos/PullOverSurBancPoulieHaute.mp4", "Dos", "1- Placez le banc dos à la poulie qui aura été placée en position haute ainsi que la barre que vous aurez accroché à la poulie. </br> 2- Prenez la barre en main et assayez-vous sur le banc, les bras doivent être tendus au dessus de votre tête. </br> 3- En faisant un arc de cercle et tout en expirant, amenez la barre au niveau du bassin tout en gardant les bras tendus. </br> 4- Après avoir gardé la contraction pendant une seconde relâchez lentement en faisant le mouvement en arc de cercle inverse, tout en gardant les bras tendus. </br> 5- Veillez à garder les bras tendus et le mouvement se fait uniquement avec les épaules. Soufflez à la contraction et inspirez au relâchement.", "- Banc. </br> - Poulie"),
("Rowing barre allongé sur un banc", "/videos/Dos/RowingAllongeSurBanc.mp4", "Dos", "1- Placez une barre chargée sous un banc et allongez vous dessus. </br> 2- Saisissez la barre et tirez la barre vers les abdominaux. </br> 3- Gardez la contraction pendant une seconde puis relâchez lentement. </br> 4- Veillez à mettre votre tête en dehors du banc, penez à toujours expirez au moment de contracter puis inspirer quand vous revenez à la position initiale.", "- Banc. </br> - Barre avec des poids."),
("Rowing barre prise supination", "/videos/Dos/RowingBarre.mp4", "Dos", "1- Prenez et chargez une barre, placez vos pieds largeur de bassin, flechissez les genoux et penchez vous afin de saisir fermement la barre en prise supination (paumes de mains vers le ciel). </br> 2- Contractez vos abdominaux afin de garder le dos droit et décollez la barre du sol. </br> 3- Amenez la barre vers vos abdominaux en gardant les coudes contre le corps lors du mouvement. </br> 4- Gardez la contraction durant une seconde puis reprenez la position de départ sans poser la barre au sol. </br> 5- Veillez à bien gainer pour vous éviter une blessure au dos, veillez également à bien respirer durant l'exercice, ne le faites pas en apnée.", "- Barre avec des poids"),
("Rowing inversé", "/videos/Dos/RowingInversé.mp4", "Dos", "1- Prenez place sous la barre du rack à squat, qui aura été placée au alentours de 1m20 du sol, afin d'avoir le dos à quelques centimètres du sol une fois que vous vous accrochez à la barre. </br> 2- Allongez votre corps afin qu'il n'y ait que les talons qui touchent le sol, le but de l'exercice sera de tirer votre corps afin d'approcher votre poitrine vers la barre. </br> 3- Contractez les abdominaux afin de rester droit comme une planche puis tirer afin d'amener votre poitrine au niveau de la barre. </br> 4- Après une contraction d'une seconde vous pouvez relâchez lentement afin de tendre de nouveau vos bras. </br> 5- Veillez à bien gainer, expirer en tirant votre corps et inspirer lors du relâchement.", "- Barre du rack à squat"),
("Rowing haltères sur banc", "/videos/Dos/RowingSurBancHaltere.mp4", "Dos", "1- Prenez un haltère et placez la main libre ainsi que le genou du même côté sur le banc, l'autre pied servira d'appui, le bras tenant l'haltère est tendu au dessus du sol. </br> 2- Expirez tout en ramenant l'haltère à hauteur des abdominaux tout en gardant le coude serré contre le corps. </br> 3- Gardez la contraction durant une seconde puis relâchez et revenez en position bras tendu vers le sol. </br> 4- Veillez à bien gainer les badominaux pour permettre au buste de rester fixe, expirez lors de l'effort et inspirez au moment de relâcher.", "- Banc. </br> - Haltère."),
("Soulevé de terre jambes tendues", "/videos/Jambes/SDTJambesTendues.mp4", "Jambes", "1- Prenez une barre à squat et chargez la à votre convenance. </br> 2- Placez vos pieds largeur de bassin, fléchissez les jambes de manière à soulever facilement la barre, gardez le dos droit et soulevez la barre. </br> 3- Le dos bien droit, les genoux légèrement fléchis, les abdominaux gainés, vous allez descendre la barre jusqu'à vos tibias sans plier les jambes et en gardant le dos bien droit. </br> 4- Faites ensuite le mouvement inverse afin de remonter la barre à la position initiale tout en gardant le dos bien droit. </br> 5- Veillez à bien gainer les abdominaux pour vous éviter une blessure au dos, inspirez en descendant la barre et expirez en la remontant.", "- Barre avec des poids"),
("Soulevé de terre au rack à squat", "/videos/Dos/SDTRackSquat.mp4", "Dos, jambes", "1- Placez la barre du rack à squat au plus bas et chargez la à votre convenance. </br> 2- Placez vous face à cette barre, les pieds largeur de bassin, le dos bien droit, vous allez fléchir les jambes afin de saisir la barre. </br> 3- Vous allez ", "- Barre du rack à squat"),
("Rowing barre prise pronation", "/videos/Dos/TirageBarre.mp4", "Dos", "1- Chargez la barre avec des poids à votre convenance. </br> 2- Placez-vous face à la barre, pieds largeur de bassin. </br> 3- Baissez vous pour décoller la barre du sol et mettez vous droit, genoux légèrement fléchis. </br> 4- Penchez votre buste afin d'avoir le corps parallèle au sol tout en gardant les genoux fléchis. </br> 5- Tirez la barre en l'amenant vers vos abdominaux tout en gardant les coudes proche du corps. </br> 6- Relâchez le mouvement lentement en amenant la barre vers le sol. </br> 7- Veillez à gainer les abdominaux afin de garder le dos droit, les genoux légèrement fléchis, expirez en montant la barre et inspirez en la descendant.", "- Barre avec des poids"),
("Rowing Landmine barre", "/videos/Dos/TirageBarreFixe.mp4", "Dos", "Chargez un côté de la landmine barre à votre convenance. </br> 2- Placez vous par dessus la barre, un pied de chaque côté de la barre, pieds largeur du bassin, genoux fléchis. </br> 3- Penchez votre buste pour saisir la barre avec vos deux mains, décollez la barre. </br> 4- Amenez la barre au plus proche de votre corps en gardant les coudes contre le corps. </br> 5- Relâchez la barre lentenment jusqu'à tendre les bras. </br> 6- Veillez à bien gainer les abdominaux afin de ne pas vous blesser le dos, expirez en contractant et inspirer en relâchant.", "- Landmine barre avec des poids"),
("Tirage horizontal à la machine", "/videos/Dos/TirageHorizontageMachine.mp4", "Dos", "1- Chargez la machine à votre convenance et prenez place sur le siège en placant votre buste sur la mousse. </br> 2- Saisissez les deux poignées et tirez les poignées vers vous tout en gardant vos coudes proche du corps. </br> 3- Relâchez lentement afin de tendre les bras sans reposer les poids. </br> 4- Veillez à bien expirer lors de la contraction et inspirer lors du relâchement.", "- Machine de tirage horizontal"),
("Tirage horizontal à la poulie", "/videos/Dos/TirageHorizontalePoulie.mp4", "Dos", "1- Positionnez la poulie en position basse et accrochez y les poignées en forme de triangle. </br> 2- Saisissez les poignées, placez vos pieds largeur de bassin, fléchissez les genoux et gainez les abdominaux. </br> 3- Tirer les poignées afin de les amener au niveau de vos abdominaux tout en gardant les coudes proches du corps. </br> 4- Relâchez lentement afin de tendre les bras. </br> 5- Veillez à bien gainer, soufflez pendant la contraction et inspirez pendant le relâchement.", "- Poulie"),
("Tirage horizontal prise serrée à la poulie", "/videos/Dos/TirageHorizontalPriseSerree.mp4", "Dos", "1- Prenez place sur le banc du tirage horizontal à la poulie et ajustez le poid à votre convenance. </br> 2- Saisissez les poignées en forme de triangle, tendez les jambes en gardant un fléchissement au niveau des genoux et gainez afin de garder le dos droit. </br> 3- Tout en expirant tirez les poignées vers vos abdominaux, gardez les coudes proches du corps. </br> 4- Expirez et relâchez le mouvement afin de tendre complètement les bras. </br> 5- Veillez à gainer les abdominaux afin de ne pas vous blesser au niveau du dos.", "- Poulie"),
("Tirage vertical à la poulie", "/videos/Dos/TirageVertical.mp4", "Dos", "1- Choisissez le poid qui vous conviendra et prenez place sur la banc du tirage vertical en plaçant vos jambes sous les boudins. </br> 2- Saisissez la barre en hauteur, les mains écartées plus larges que les épaules. </br> 3- Tirez la barre afin d'amener cette barre au niveau de votre menton, gardez la contraction durant une seconde. </br> 4- Relâchez doucement afin de tendre les bras pour reprendre la position initiale. </br> 5- Veillez a bien expirer lors de la contraction et inspirer au moment de relâcher.", "- Poulie"),
("Rowing barre au rack à squat", id 54),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
(),
